### ISSUE TITLE
secondary_directory_servers is no longer supported

### ISSUE THREAD

**Issue by ghost** [PC-Admin/PC-Admin-s-Synapse-Setup-Guide#1]
Hi PC-Admin. Just looking over your tutorial and noticed that it advises tweaking `secondary_directory_servers:` in `homeserver.yaml`. However, this setting is no longer supported (Since Sep 2016) as you can see in https://github.com/matrix-org/synapse/commit/413138112379594bf9290576d44c365af612817d#diff-7604431227e17cc581f690570dfacca6 . Regards, Coffee

**Comment by PC-Admin** [comment]
This part has been edited out, thank you for the suggestion.
