### ISSUE TITLE
Add self hosted ma1sd Matrix Identity Server into the mix

### ISSUE THREAD

**Issue by schnuffle** [PC-Admin/PC-Admin-s-Synapse-Setup-Guide#12]
I'm playing around with the ma1sd integration into my matrix stack. 

I think that is a part that should also be mentioned as it is often overlooked and creates a dependency to the matrix.org identity service that is  problematic on a privacy level.

I can add the setup of ma1sd and the integration to your document in case you're intrested in.

Regards

Schnuffle

**Comment by PC-Admin** [comment]
Hello Schnuffle,

It depends how reliable the ma1sd is, and how modular the install process is? 

The guide is already fairly complex, so I'm thinking it might be more appropriate to have a ma1sd section in the Synapse Extras Guide: https://github.com/PC-Admin/PC-Admins-Synapse-Extras

**Comment by schnuffle** [comment]
Hi PC-Admin,
how reliable it is, I can only answer after having it used for a while :-). 
Putting it in the Extras Guide sounds reasonable for me. 
I'll test it for some time and in case I think it's worth adding, I'll make a PR to https://github.com/PC-Admin/PC-Admins-Synapse-Extras

Regards

Schnuffle

P.S.: Feel free to close the issue

**Comment by PC-Admin** [comment]
That would be awesome, thank you for the contribution. :)

PC-Admin

**Comment by PC-Admin** [comment]
@schnuffle any update on this? i ended up removing the Jitsi section since running 2 coturn servers was buggy and it didn't even make sense :D an update for ma1sd would be awesome

**Comment by schnuffle** [comment]
Back from holidays, so ready for new playgrounds :-).
I have it still running, so will see what needs to be done to integrate it into your stack.

For the turnserver, i don't use jitsi but a BBB server and synapse and BBB use the same turnserver without a problem for the moment

Regards

Marc

**Comment by PC-Admin** [comment]
The current setup has no Jitsi in it, the ma1sd identity server won't use turn anyway though. Would be an awesome upgrade to this installation guide.

Thanks again :)
