### ISSUE TITLE
Consider adding a LICENSE

### ISSUE THREAD

**Issue by ghost** [PC-Admin/PC-Admin-s-Synapse-Setup-Guide#2]
Even if it just says:
>(c) You, all rights reserved.

Clarity is wonderful.

Of course I'm hoping you'll consider actually open sourcing it, so someone can take it over if it becomes abandoned. (If not already.)

**Comment by PC-Admin** [comment]
It's now licensed under Creative Commons Attribution Share Alike 4.0.
