### ISSUE TITLE
will be nice an update to work with Py3

### ISSUE THREAD

**Issue by elaur** [PC-Admin/PC-Admin-s-Synapse-Setup-Guide#7]
Will be nice to update a bit this guide to work with py3 and the new acme ssl certificate support ...

**Comment by PC-Admin** [comment]
i'd welcome a pull request if you could make one

**Comment by schnuffle** [comment]
Using a debian package, there shouldn't be anything to change as it's defined by the package which python version is used

Regards Schnuffle

**Comment by PC-Admin** [comment]
done, thanks for the feedback
